Repository mashoodshaukat00/EcoCarpet, pull requests merged in 2025-04, with the labels that each got.

#54 Feature/#53 redefine relationship between entities
  EcoCarpet/EcoCarpet.Server/Controllers/SubscriptionController.cs
  EcoCarpet/EcoCarpet.Server/Controllers/UserController.cs
  EcoCarpet/EcoCarpet.Server/Controllers/UserSubscriptionController.cs
  EcoCarpet/EcoCarpet.Server/Data/AppDbContext.cs
  EcoCarpet/EcoCarpet.Server/EcoCarpet.Server.csproj
  EcoCarpet/EcoCarpet.Server/Migrations/20250127113004_InitialCreate.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250127113004_InitialCreate.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250129110907_as.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250129110907_as.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250129113717_sd.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250129113717_sd.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250129142025_carpet.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250130102553_er.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250130102553_er.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250130104404_RenameCustomerTableToUser.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250130104404_RenameCustomerTableToUser.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250130123648_UserRenameChanges.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250130123648_UserRenameChanges.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250203130658_CreateSubscriptionTables.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250217114709_addImgName.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250217114709_addImgName.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250303111658_initial.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250303111658_initial.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250310151019_AddCarpetOrderPaymentTables.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250310151019_AddCarpetOrderPaymentTables.cs
  EcoCarpet/EcoCarpet.Server/Migrations/AppDbContextModelSnapshot.cs
  EcoCarpet/EcoCarpet.Server/Models/Carpet.cs
  EcoCarpet/EcoCarpet.Server/Models/Order.cs
  EcoCarpet/EcoCarpet.Server/Models/OrderDetail.cs
  EcoCarpet/EcoCarpet.Server/Models/Payment.cs
  EcoCarpet/EcoCarpet.Server/Models/Subscription.cs
  EcoCarpet/EcoCarpet.Server/Models/User.cs
  EcoCarpet/EcoCarpet.Server/Models/UserSubscription.cs
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/CartPage/cartPage.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/RegistrationForm.jsx
Labels: enhancement

#61 Add logout functionality
  EcoCarpet/EcoCarpet.Server/Migrations/20250410101206_UpdateUserEntity.Designer.cs
  EcoCarpet/EcoCarpet.Server/Migrations/20250410101206_UpdateUserEntity.cs
  EcoCarpet/EcoCarpet.Server/Models/User.cs
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/CartPage/cartPage.jsx
  EcoCarpet/ecocarpet.client/src/components/Login/Login.jsx
  EcoCarpet/ecocarpet.client/src/components/Logout/Logout.jsx
  EcoCarpet/ecocarpet.client/src/components/Nav/Nav.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/RegistrationForm.jsx
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useAuth.js
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useLoginForm.js
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useRegistrationForm.js
Labels: enhancement, Feature

#63 tried and tested React query
  EcoCarpet/ecocarpet.client/package-lock.json
  EcoCarpet/ecocarpet.client/package.json
  EcoCarpet/ecocarpet.client/src/components/CartPage/cartPage.jsx
  EcoCarpet/ecocarpet.client/src/components/Login/Login.jsx
  EcoCarpet/ecocarpet.client/src/main.jsx
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useLoginForm.js
Labels: enhancement

#66 subscription page design completed
  EcoCarpet/ecocarpet.client/src/components/Subscriptions/SubscriptionPage.jsx
Labels: Feature

#69 Feature/#68 clean cartlist component
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetDetails/CarpetDetails.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetList/Carpet.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetList/CarpetList.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetList/Filter.jsx
  EcoCarpet/ecocarpet.client/src/components/Cart/Cart.jsx
Labels: Improvment

#73 Feature/#11 cart page
  EcoCarpet/ecocarpet.client/package-lock.json
  EcoCarpet/ecocarpet.client/package.json
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/Carousel/Carousel.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetDetails/CarpetDetails.jsx
  EcoCarpet/ecocarpet.client/src/components/Cart/Cart.jsx
  EcoCarpet/ecocarpet.client/src/components/Subscriptions/SubscriptionPage.jsx
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useCarpetDetails.js
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useCart.jsx
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useCartPageActions.js
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useSubscriptions.js
Labels: Feature

#74 Feature/#67 checkout component
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/Checkout/Checkout.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/RegistrationForm.jsx
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useRegistrationForm.js
Labels: Feature

#75 create payment and success page
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/Checkout/Checkout.jsx
  EcoCarpet/ecocarpet.client/src/components/Payment/Payment.jsx
  EcoCarpet/ecocarpet.client/src/components/Success/Success.jsx
  EcoCarpet/ecocarpet.client/src/utilities/hooks/usePaymentForm.js
Labels: Feature

#76 fix styling issues
  EcoCarpet/ecocarpet.client/src/components/Carousel/Carousel.jsx
  EcoCarpet/ecocarpet.client/src/components/Carousel/Style.css
  EcoCarpet/ecocarpet.client/src/components/CarpetDetails/CarpetDetails.jsx
Labels: Improvment

#77 Misc changes and improvements in the project.
  EcoCarpet/ecocarpet.client/public/images/rug_collection.jpg
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/About/About.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetDetails/CarpetDetails.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetList/Carpet.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetList/CarpetList.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetList/Filter.jsx
  EcoCarpet/ecocarpet.client/src/components/Cart/Cart.jsx
  EcoCarpet/ecocarpet.client/src/components/Footer/Footer.jsx
  EcoCarpet/ecocarpet.client/src/components/Home/Home.jsx
  EcoCarpet/ecocarpet.client/src/components/Login/Login.jsx
  EcoCarpet/ecocarpet.client/src/components/Logout/Logout.jsx
  EcoCarpet/ecocarpet.client/src/components/Nav/EcoCarpetLogo.jsx
  EcoCarpet/ecocarpet.client/src/components/Nav/Nav.jsx
  EcoCarpet/ecocarpet.client/src/components/Payment/Payment.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/RegistrationForm.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/RegistrationForm.module.css
  EcoCarpet/ecocarpet.client/src/utilities/hooks/usePaymentForm.js
  EcoCarpet/ecocarpet.client/src/utilities/hooks/useRegistrationForm.js
Labels: enhancement, Feature, Improvment
