Repository mashoodshaukat00/EcoCarpet, pull requests merged in 2025-02, with the labels that each got.

#38 integrate tailwindcss
  EcoCarpet/ecocarpet.client/package-lock.json
  EcoCarpet/ecocarpet.client/package.json
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/index.css
  EcoCarpet/ecocarpet.client/vite.config.js
Labels: enhancement

#39 add api to fetch data from database. create component and fetch data …
  EcoCarpet/EcoCarpet.Server/Controllers/CarpetController.cs
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/ProductList/ProductList.jsx
Labels: enhancement, Feature

#44 Feature/#32 style registration page
  EcoCarpet/ecocarpet.client/package-lock.json
  EcoCarpet/ecocarpet.client/package.json
  EcoCarpet/ecocarpet.client/src/App.css
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/Footer/Footer.jsx
  EcoCarpet/ecocarpet.client/src/components/Home/Home.jsx
  EcoCarpet/ecocarpet.client/src/components/Nav/Nav.jsx
  EcoCarpet/ecocarpet.client/src/components/NoPage/NoPage.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/Registration.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/RegistrationForm.jsx
  EcoCarpet/ecocarpet.client/src/index.css
Labels: Feature

#50 add env variable to fix localhost port issue.
  EcoCarpet/ecocarpet.client/src/App.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetDetails/CarpetDetails.jsx
  EcoCarpet/ecocarpet.client/src/components/CarpetList/CarpetList.jsx
  EcoCarpet/ecocarpet.client/src/components/Login/Login.jsx
  EcoCarpet/ecocarpet.client/src/components/Registratioin/RegistrationForm.jsx
  EcoCarpet/ecocarpet.client/src/components/Subscriptions/SubscriptionPage.jsx
Labels: bug

#52 populate subscription table and remove "delete controller".
  EcoCarpet/EcoCarpet.Server/Controllers/CarpetController.cs
  EcoCarpet/EcoCarpet.Server/Controllers/SubscriptionController.cs
  EcoCarpet/EcoCarpet.Server/Models/UserSubscription.cs
  EcoCarpet/ecocarpet.client/src/components/Subscriptions/SubscriptionPage.jsx
Labels: enhancement
